# Change these first
owner: jemmorey
repo: upptime

sites:
  - name: SpeakUpConference.com
    url: https://www.speakupconference.com
    maxResponseTime: 5000
  - name: SpeakUpForHope.org
    url: https://www.speakupforhope.org
    maxResponseTime: 5000
  - name: CarolKent.org
    url: https://carolkent.org
    maxResponseTime: 5000
  - name: SpeakUpMinistries.com
    url: https://www.speakupministries.com
    maxResponseTime: 5000
  - name: SpeakUpSpeakerServices.com
    url: https://www.speakupspeakerservices.com
    maxResponseTime: 5000
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /jemmorey/upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: JEmmorey Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Uptime Report for Speakup Aligned Websites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
